[book]
title = "Libra's Move Book for beginners"
description = "First Book about Libra's Move language and Move VM. Move documentation, tutorials and language reference"
authors = ["Damir Shamanaev"]
language = "en"
multilingual = false
src = "docs"

[output.html]
google-analytics = "UA-93092448-16"
git-repository-url = "https://github.com/damirka/move-book"
git-repository-icon = "fa-github"
