[book]
title = "Libra's Move Book for beginners"
description = "First book about Libra's Move programming language and Move VM. Move documentation, Move tutorials and language reference"
authors = ["Damir Shamanaev"]
language = "en"
multilingual = false
src = "docs"

[output.html]
# google-analytics = "UA-93092448-16"
git-repository-url = "https://github.com/damirka/move-book"
git-repository-icon = "fa-github"
