[book]
title = "The Move Book"
description = "First book about Diem's Move programming language and Move VM. Move documentation, Move tutorials and language reference"
authors = ["Damir Shamanaev"]
language = "en"
multilingual = false
src = "docs"

[output.html]
google-analytics = "UA-183817972-1"
git-repository-url = "https://github.com/damirka/move-book"
git-repository-icon = "fa-github"
